config:
  eureka:
    server:
      context-path: /eurekaConfig
      port: 8160
  security:
    user:
      name: admin
      password: admin


springcloud:
  config:
    pwd: '{cipher}AQAPKN8QlXSL4lLmWnlS0Ig7bnmYw+Ql7K1aI25ttYpcqSHSJfHtHAbW4RPTOA3yeIMfB4MEW47tNDopaRydkArHyIRL+1yoB9FvVS0B1I2qQwjpmov+L3UIa9PYo1hrEeKn/Gkq6o6y4Liy5AyH1zGDzQfWEDF87luPJUqGL8JyxwOvNqCOllspDYa0pWLfvrhMwkMe5sfB21jbG8jlZcZvABn2BW8wAOK+9gfvexr8Ydkfrpq/a8w6B0hH9j+5Lz8VTg6BNgEJtvUs66x/PoE9Z+dnIS6bVjbpI5skMB/9p2M5A6y6ShtDADl8o2tPUH58Sc286OZjm1nh9IHt0tuo3gkKsgdee/0jDoJGUvcjXYu5AdwuggCTJRtSQEl3h8U='
    git:
     user: ChangJing89
     pwd: '{cipher}AQCb8QX+OzaHnQ8zSLQRN5xRXQ1XpxX2DgmMqAFhFQZA5KFTj6d7uACQZMi0B/8wZyBd7fFU2a+I1KvQtwl3h1CV2fH/gscYzYl7CEi8DItEjC8NJdQC/4Ug8a5ruyEl4Ke57Fxt03rFbpAQ8hsAZzSoZ2tuteov3XKcJHPHNncEnKsTjIjvkjckE32dZk1wSY+frOlByIApGiFKKZFxJY5JZYCgdvRvJZFd/cdWKKZthLOMgXBubvseRGMZq5fm1H7LVQuMlt9uPlrDa/fWxF3HJhhUdgzIdJFviE3p6nYLKg7Vc9wvm3+qEvoi8/yYxQHFBQ5/MEYaU2IUH07He6IrEc65+kwFf0Fryj891iWSfxnsQJkEP3wtaWxVXogrG7U='

spring:
  security:
    config:
      user:
        name: configAdmin
        pwd: '{cipher}AQBmC+XAaIcWJzMEuqUekikvcQRpOJJZIT41tsvzsH7iu8WX19PlqtQs9Xt+80BL5so8zuT1S9BTXU9V+V891U35igFMo8vuOalqyb0tHO+kXqDEQRNTJ5eWJENMXCsJBqd+n/QUyJdMmd/ElB0Lug5mc2TkIAlReX5EuqKBfpbSvcT3MiRAdbfaxu/T6T6ElZbdyTU1VW16r/iyi48bQOOnV/pnRCiE7rRoUN6HA9wEafklTKF0zdVHM/qQ+CzuNHh7g+HpnkfWFfFyjM2kXW3Sjga3u+nMkY4fmB3YiTu5lNIbcbSbAKVeXTTwb4Wsef7ow1J6f+Ao3oZ+TLC0jQ7tTBwL6jH8DceWCcFOqa4HqIFh0SIBPj3DeNDUrlvDYoA='
