postgres:
  url: jdbc:postgresql://172.16.65.103:31072/postgres?currentSchema=demo&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
  username: gpadmin
  password: Rd123456
  driver-class-name: org.postgresql.Driver
  
jpa:
  database-platform: org.hibernate.dialect.PostgreSQL9Dialect

eureka:
  url: order-eureka.apps.pas.cloud.dhc.com.cn
