mysql:
  url: jdbc:mysql://localhost:3306/sys?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
  username: root
  password: C890408j
  driver-class-name: com.mysql.cj.jdbc.Driver
  
jpa:
  database-platform: org.hibernate.dialect.MySQL5Dialect

eureka:
  instance: localhost
  port: 8011
