mysql:
  url: jdbc:mysql://172.16.65.95:32483/demo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
  username: root
  password: 123456

eureka:
  url: order-eureka.apps.pas.cloud.dhc.com.cn
