mysql:
  url: jdbc:mysql://localhost:3306/sys?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
  username: root
  password: C890408j

eureka:
  url: order-eureka.apps.pas.cloud.dhc.com.cn
